config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :events do
    resources :roles
    resources :attendees do
      collection do
        get :import
        post :import_csv
        get :export
        get :export_blanks
      end
    end
  end

  root "home#index"
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
  belongs_to :role

  def self.alphabetical
    order("last_name asc, first_name asc")
  end

  def self.pending
    where(exported: false)
  end

  def name
    [first_name, last_name].join(" ")
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :authorize!
  before_action :find_attendee, only: [:show, :edit, :update, :destroy]
  before_action :find_event

  def index
    @q = @event.attendees.ransack(params[:q])
    @attendees = @q.result.alphabetical.includes(:role)
  end

  def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.new(attendee_params.merge(exported: false))

    if @attendee.save
      redirect_to event_attendees_path(params[:event_id])
    else
      render :new
    end
  end

  def update
    if @attendee.update_attributes(attendee_params)
      flash[:notice] = "Successfully updated attendee."
      redirect_to event_attendees_path(@attendee.event)
    else
      flash[:alert] = "Unable to update attendee."
      render :edit
    end
  end

  def destroy
    if @attendee.destroy
      flash[:notice] = "Successfully removed attendee #{@attendee.name}."
      redirect_to event_attendees_path
    else
      flash[:alert] = "Unable to remove attendee #{@attendee.name}."
      redirect_to event_attendees_path
    end
  end

  def import_csv
    result = ImportAttendees.call({event: @event}.merge(import_params))

    if result.success?
      flash[:notice] = "Imported Attendees"
      redirect_to event_attendees_path
    else
      flash[:alert] = result.message
      redirect_to import_event_attendees_path
    end
  end

  def export
    attendees = Attendee.pending.alphabetical.includes(:role)
    if attendees.present?
      result = ExportAttendees.call(attendees: attendees)
      send_data result.pdf.render, filename: 'badges.pdf', type: 'application/pdf', disposition: 'inline'
    else
      flash[:alert] = "No Attendees to Export (PDF)"
      redirect_to event_attendees_path(@event)
    end
  end

  def export_blanks
    result = ExportAttendees.call(blanks: true, event: @event)
    send_data result.pdf.render, filename: 'blank_badges.pdf', type: 'application/pdf', disposition: 'inline'
  end

  private

  def find_attendee
    @attendee = Attendee.find(params[:id])
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def import_params
    params.permit(:file)
  end

  def attendee_params
    params.require(:attendee).permit(
      :first_name, :last_name, :email, :company, :role_id, :checked_in,
      :twitter_handle, :shirt_size, :dietary_restrictions, :event_id
    )
  end
end

app/views/attendees/_attendees.html.erb
<% attendees.each do |attendee| %>
  <tr>
    <td>
      <%= form_for [@event, attendee], remote: true do |form| %>
        <%= form.check_box :checked_in %>
      <% end %>
    </td>
    <td><%= attendee.last_name %></td>
    <td><%= attendee.first_name %></td>
    <td><%= attendee.shirt_size %></td>
    <td>
      <%= link_to "Edit", edit_event_attendee_path(attendee.event, attendee) %>
      <% if current_user.super_admin %>
        <%= link_to "Remove", event_attendee_path(attendee.event, attendee), method: :delete %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/attendees/_form.html.erb
<%= form_for [@event, attendee] do |form| %>
  <%= form.hidden_field :event_id, value: params[:event_id] %>
  <%= form.label :first_name, "First Name" %>
  <%= form.text_field :first_name %>
  <%= form.label :last_name, "Last Name" %>
  <%= form.text_field :last_name %>
  <%= form.label :email, "Email" %>
  <%= form.text_field :email %>
  <%= form.label :company, "Company" %>
  <%= form.text_field :company %>
  <%= form.label :twitter_handle, "Website/Twitter" %>
  <%= form.text_field :twitter_handle %>

  <%= select "attendee", :role_id, options_for_select(@event.roles.uniq.map {|role| [role.name, role.id] }) %>

  <%= form.submit %>
<% end %>

app/views/attendees/edit.html.erb
<h2>Edit Attendee</h2>
<%= render "form", attendee: @attendee %>

app/views/attendees/import.html.erb
<%= form_tag(import_csv_event_attendees_path, multipart: true, method: :post) do %>
  <%= label_tag :file, "Select .CSV file" %>
  <%= file_field_tag :file %>
  <%= submit_tag %>
<% end %>

app/views/attendees/index.html.erb
<h2>Attendees</h2>

<div class="pull-right">
  <%= link_to "Add Attendee", new_event_attendee_path, class: 'btn' %>

  <% if current_user.admin %>
    <%= link_to "Import Attendees", import_event_attendees_path, class: 'btn' %>
    <%= link_to "Generate Badges", export_event_attendees_path, class: 'btn' %>
  <% end %>
</div>

<%= search_form_for @q, remote: true, url: event_attendees_path(@event) do |f| %>
  <%= f.search_field :first_name_or_last_name_cont, placeholder: "Search by first or last name", autocomplete: "off" %>
<% end %>

<table class="attendees-table">
  <tr>
    <th>Here?</th>
    <th>Last</th>
    <th>First</th>
    <th>Shirt Size</th>
    <th></th>
  </tr>
  <tbody data-attendees-content>
    <%= render "attendees", attendees: @attendees %>
  </tbody>
</table>

app/views/attendees/index.js.erb
$("[data-attendees-content]").html('<%= escape_javascript(render("attendees", attendees: @attendees)) %>');

$("input[id=attendee_checked_in]").on("change", function() {
  console.log("checked in")
  $(this).closest("form").submit();
});

app/views/attendees/new.html.erb
<h2>Add Attendee</h2>
<%= render "form", attendee: @attendee %>