config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :events do
    resources :roles
    resources :attendees do
      collection do
        get :import
        post :import_csv
        get :export
        get :export_blanks
      end
    end
  end

  root "home#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :logo, LogoUploader

  has_many :attendees
  has_many :roles, through: :attendees
  has_many :sponsor_companies
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize!
  before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def update
    if @event.update_attributes(event_params)
      flash[:notice] = "Successfully updated event."
      redirect_to events_path
    else
      flash[:alert] = "Unable to update event."
      render :edit
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = "Successfully removed event #{@event.name}."
      redirect_to events_path
    else
      flash[:alert] = "Unable to remove event."
      redirect_to events_path
    end
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :logo, :start_date, :end_date)
  end
end

app/views/events/_form.html.erb
<%= form_for @event do |form| %>
  <%= form.label :name, "Event Name" %>
  <%= form.text_field :name %>
  <%= form.label :logo, "Logo" %>
  <meta>This logo will the image used if you want to print the logo on a badge.</meta>
  <%= form.file_field :logo %>
  <%= form.label :start_date, "Date Event Starts" %>
  <%= form.date_field :start_date %>
  <%= form.label :start_date, "Date Event Ends" %>
  <%= form.date_field :end_date %>

  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h2>Edit Event</h2>
<%= render "form", event: @event %>

app/views/events/index.html.erb
<h2>Events</h2>

<% if current_user.super_admin %>
  <%= link_to "Add Event", new_event_path %>
<% end %>

<table>
  <tr>
    <th>Event Name</th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td>
        <%= link_to "View Attendees", event_attendees_path(event) %>
        <% if current_user.super_admin %>
          <%= link_to "Edit", edit_event_path(event) %>
          <%= link_to "Remove", event_path(event), method: :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h2>New Event</h2>
<%= render "form", event: @event %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>

<%= link_to "View Attendees", event_attendees_path(@event) %>
<%= link_to "Generate Badges", export_event_attendees_path(@event) %>


<%= link_to "Edit", edit_event_path(@event) %>
<%= link_to "Remove", event_path(@event), method: :delete %>
<div>
<%= image_tag(@event.logo) %>
</div>
<h3>Roles</h3>
<ul>
<% @event.roles.uniq.each do |role| %>
  <li style="background-color: #<%= role.border_color %>"><%= link_to role.name, event_role_path(@event, role) %></li>
<% end %>
</ul>

<h3>Sponsors</h3>
<ul>
<% @event.sponsor_companies.each do |sponsor| %>
  <li><%= sponsor.company %></li>
<% end %>
</ul>